// This is where everything to do with drawing happens.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "graphics.h"
#include "scripting.h" // For the draw mode defines only
#include "string_stuff.h" // For a bit of string slicing
#include "main.h"
#include "new_editor.h" // For the list of graphics in the big list thing
#include "output.h"
#include "global_param_list.h"

#include "fortify.h"
#include "file_stuff.h"



void GRAPHICS_load_graphics()
{
	// This loads up all the sprites and miscellaneous other graphics from the various folders using
	// the text files generated by the parser. Files come in two flavours:
	// (1) Set size sprite sheets - these are the easiest as they have sprites which are all the same size.
	// (2) Arbitrary size sprite sheets - these require a descriptor file (same name, different extension)
	//     which says where the frames are and how big they are on the sheet. This data is created either
	//     manually or by a program as it is in text form.

	// Load the sprites first...

	bool flag = true;
	char filename[MAX_NAME_SIZE];
	char full_filename[MAX_NAME_SIZE];
	char text_desc_filename[MAX_NAME_SIZE];
	char *word_pointer;
	int frame_width;
	int frame_height;

	int pivot_x,pivot_y;
	int bitmap_number;
	int letter_counter;

	int list_start,list_end;
	int list_pointer;

	GPL_list_extents ("SPRITES", &list_start, &list_end);
	char *extension_pointer = GPL_what_is_list_extension ("SPRITES");
	if ((list_start == UNSET) || (list_end == UNSET) || (extension_pointer == NULL))
	{
		MAIN_add_to_log("SPRITES list missing or invalid in global parameter list.");
		return;
	}

	#ifdef RETRENGINE_DEBUG_VERSION_THE_LAST_THING_I_DID
		char debug_text[MAX_LINE_SIZE];
		sprintf(debug_text,"Entered graphic loading function...");
		MAIN_debug_last_thing (debug_text);
	#endif

	for (list_pointer = list_start; list_pointer < list_end ; list_pointer++)
	{
		// Okay, check the file to see if it contains the "-arb" or "-set"

		#ifdef RETRENGINE_DEBUG_VERSION_THE_LAST_THING_I_DID
			sprintf(debug_text,"About to get filename.",filename);
			MAIN_debug_last_thing (debug_text);
		#endif

		sprintf (filename , "%s%s" , GPL_what_is_word_name (list_pointer) , extension_pointer );

		#ifdef RETRENGINE_DEBUG_VERSION_THE_LAST_THING_I_DID
			sprintf(debug_text,"Got filename '%s'.",filename);
			MAIN_debug_last_thing (debug_text);
		#endif

		if (load_from_dat_file)
		{
			strcpy(full_filename,filename);

			#ifdef RETRENGINE_DEBUG_VERSION_THE_LAST_THING_I_DID
				sprintf(debug_text,"Copied '%s' to '%s'.",filename,full_filename);
				MAIN_debug_last_thing (debug_text);
			#endif
		}
		else
		{
			FILE_append_filename(full_filename, "sprites", filename, sizeof(full_filename));
		}

		word_pointer = strtok(filename,"[].");
		word_pointer = strtok(NULL,"[].");
		if (word_pointer == NULL)
		{
			char skip_text[MAX_LINE_SIZE];
			sprintf(skip_text, "Skipping malformed sprite entry '%s'.", GPL_what_is_word_name(list_pointer));
			MAIN_add_to_log(skip_text);
			continue;
		}

		if ( strcmp(word_pointer,"SET") == 0 ) // it's a set type! Hurrah! This means they are all the same...
		{
			word_pointer = strtok(NULL,"[].");
			if (word_pointer == NULL) { continue; }
			frame_width = atoi(word_pointer);

			word_pointer = strtok(NULL,"[].");
			if (word_pointer == NULL) { continue; }
			frame_height = atoi(word_pointer);

			word_pointer = strtok(NULL,"[].");
			if (word_pointer == NULL) { continue; }
			pivot_x = atoi(word_pointer);

			word_pointer = strtok(NULL,"[].");
			if (word_pointer == NULL) { continue; }
			pivot_y = atoi(word_pointer);

			#ifdef RETRENGINE_DEBUG_VERSION_THE_LAST_THING_I_DID
				sprintf(debug_text,"About to load file %s",full_filename);
				MAIN_debug_last_thing (debug_text);
			#endif

			if (load_from_dat_file)
			{
				bitmap_number = INPUT_load_bitmap (full_filename); // Because we're just using the filename to find the stuff in the packfile.

				#ifdef RETRENGINE_DEBUG_VERSION_THE_LAST_THING_I_DID
					sprintf(debug_text,"Loaded file %s",full_filename);
					MAIN_debug_last_thing (debug_text);
				#endif
			}
			else
			{
				bitmap_number = INPUT_load_bitmap (MAIN_get_project_filename (full_filename));
			}

			INPUT_create_equal_sized_sprite_series (bitmap_number, "IMAGE", frame_width, frame_height, pivot_x, pivot_y);
		}
		else if ( strcmp(word_pointer,"ARB") == 0 ) // It's arbitrarily sized, which means finding every last ikkle wikkle sprite in the bugger by eliminating areas of a given colour.
		{
			strcpy (text_desc_filename,full_filename);
			letter_counter = STRING_instr_char (text_desc_filename , '.' , 0);
			sprintf (&text_desc_filename[letter_counter],".TXT");

			#ifdef RETRENGINE_DEBUG_VERSION_THE_LAST_THING_I_DID
				sprintf(debug_text,"About to load file %s",full_filename);
				MAIN_debug_last_thing (debug_text);
			#endif

			if (load_from_dat_file)
			{
				bitmap_number = INPUT_load_bitmap (full_filename); // Because we're just using the filename to find the stuff in the packfile.

				#ifdef RETRENGINE_DEBUG_VERSION_THE_LAST_THING_I_DID
					sprintf(debug_text,"Loaded file %s",full_filename);
					MAIN_debug_last_thing (debug_text);
				#endif
					
				INPUT_create_arbitrary_sized_sprite_series (bitmap_number, "IMAGE", text_desc_filename);
			}
			else
			{
				bitmap_number = INPUT_load_bitmap (MAIN_get_project_filename (full_filename));
				INPUT_create_arbitrary_sized_sprite_series (bitmap_number, "IMAGE", MAIN_get_project_filename (text_desc_filename));
			}
		}
		else // It's not got an extension yet...
		{
		
		}

	}

}
