#ifndef _SHARED_COLLISION_DEFINES_H_
#define _SHARED_COLLISION_DEFINES_H_

#define DIRECTION_UP		0
#define DIRECTION_RIGHT		1
#define DIRECTION_DOWN		2
#define DIRECTION_LEFT		3
#define DIRECTION_INTERNAL	4

#define HORIZONTAL_AXIS			0
#define VERTICAL_AXIS			1

#define DIRECTION_BITVALUE_UP			1
#define DIRECTION_BITVALUE_RIGHT		2
#define DIRECTION_BITVALUE_DOWN			4
#define DIRECTION_BITVALUE_LEFT			8
#define DIRECTION_BITVALUE_HORIZONTAL	10
#define DIRECTION_BITVALUE_VERTICAL		5
#define DIRECTION_BITVALUE_TOTAL		15
#define DIRECTION_BITVALUE_INTERNAL		16

#endif
