if(NOT DEFINED PROJECT_SOURCE_DIR)
  message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

execute_process(
  COMMAND git -C "${PROJECT_SOURCE_DIR}" describe --tags --dirty --always
  RESULT_VARIABLE GIT_DESCRIBE_RESULT
  OUTPUT_VARIABLE GIT_DESCRIBE_OUTPUT
  ERROR_QUIET
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(NOT GIT_DESCRIBE_RESULT EQUAL 0)
  set(GIT_DESCRIBE_OUTPUT "unknown")
endif()

set(VERSION_DISPLAY "${GIT_DESCRIBE_OUTPUT}")

string(REGEX MATCH "^([^-\n]+)" VERSION_TAG_MATCH "${GIT_DESCRIBE_OUTPUT}")
if(CMAKE_MATCH_1)
  set(VERSION_DISPLAY "${CMAKE_MATCH_1}")
endif()

string(FIND "${GIT_DESCRIBE_OUTPUT}" "-dirty" DIRTY_INDEX)
if(NOT DIRTY_INDEX EQUAL -1)
  set(VERSION_DISPLAY "${VERSION_DISPLAY} DIRTY")
endif()

string(TOUPPER "${VERSION_DISPLAY}" GIT_DESCRIBE_OUTPUT_UPPER)

file(WRITE "${OUTPUT_FILE}" "MENU_VERSION_LABEL\t\t${GIT_DESCRIBE_OUTPUT_UPPER}\n")
